#Config database authentication
datasource.auth.url: jdbc:mysql://localhost:3306/database_base
datasource.auth.username: root
datasource.auth.password: 2vkDM0CGFbS3x2T2wmxa5Kpwrs4H/s26zn7CN+YMkdTeczcdIUVCAAPqMP5HxQ==
datasource.auth.driver-class-name: com.mysql.cj.jdbc.Driver
datasource.auth.packageScan : com.java.entities
datasource.auth.repository.packageScan : com.java
datasource.auth.hibernate.ddl-auto: none

inventory.logs.path: /opt/inventory/logs/production
app.aes.secret: MTIzcnVnaHRhbmtobW91dA==
upload.path: ./uploads/
qrcode.path: ./qrcodes/
file.path: files/
settings:
  firebase:
    fcm:
      setting-filename: /firebase-adminsdk.json

server:
  port: 8085
spring:
  config:
    use-legacy-processing: true
  profiles:
    include: common
